import { formatPromptNumericValue } from "./format";
import type { Prompt } from "../../types/game";

type PromptInput = Omit<Prompt, "answerDisplay"> & {
  answerDisplay?: string;
};

function definePrompt(input: PromptInput): Prompt {
  return {
    ...input,
    answerDisplay: input.answerDisplay ?? formatPromptNumericValue(input.answerNumeric, input),
  };
}

export const culturePrompts: Prompt[] = [
  definePrompt({
    id: "culture-first-oscars-categories",
    pack: "culture",
    category: "Awards",
    promptText: "Award categories at the first Academy Awards",
    unitLabel: "categories",
    unitShort: "categories",
    answerNumeric: 12,
    hintText: "Use the May 16, 1929 ceremony.",
    difficulty: 2,
    answerYear: 1929,
    sourceLabel: "Oscars",
  }),
  definePrompt({
    id: "culture-oscar-statuette-height",
    pack: "culture",
    category: "Awards",
    promptText: "Height of an Oscar statuette",
    unitLabel: "inches",
    unitShort: "in",
    answerNumeric: 13.5,
    difficulty: 2,
    sourceLabel: "Oscars",
  }),
  definePrompt({
    id: "culture-pulitzer-categories",
    pack: "culture",
    category: "Awards",
    promptText: "Pulitzer Prize categories",
    unitLabel: "categories",
    unitShort: "categories",
    answerNumeric: 23,
    difficulty: 2,
    sourceLabel: "The Pulitzer Prizes",
  }),
  definePrompt({
    id: "culture-broadway-theatres",
    pack: "culture",
    category: "Theater",
    promptText: "Broadway theatres listed by Broadway.org in 2026",
    unitLabel: "theatres",
    unitShort: "theatres",
    answerNumeric: 41,
    difficulty: 2,
    answerYear: 2026,
    sourceLabel: "Broadway.org",
  }),
  definePrompt({
    id: "culture-carnegie-hall-seats",
    pack: "culture",
    category: "Music venue",
    promptText: "Seats in Carnegie Hall's Stern Auditorium / Perelman Stage",
    unitLabel: "seats",
    unitShort: "seats",
    answerNumeric: 2_804,
    difficulty: 2,
    sourceLabel: "Carnegie Hall",
  }),
  definePrompt({
    id: "culture-piano-white-keys",
    pack: "culture",
    category: "Instrument",
    promptText: "White keys on a standard 88-key piano",
    unitLabel: "keys",
    unitShort: "keys",
    answerNumeric: 52,
    difficulty: 1,
    sourceLabel: "Steinway & Sons",
  }),
  definePrompt({
    id: "culture-piano-black-keys",
    pack: "culture",
    category: "Instrument",
    promptText: "Black keys on a standard 88-key piano",
    unitLabel: "keys",
    unitShort: "keys",
    answerNumeric: 36,
    difficulty: 1,
    sourceLabel: "Steinway & Sons",
  }),
  definePrompt({
    id: "culture-concert-harp-strings",
    pack: "culture",
    category: "Instrument",
    promptText: "Strings on a concert grand harp",
    unitLabel: "strings",
    unitShort: "strings",
    answerNumeric: 47,
    difficulty: 2,
    sourceLabel: "Lyon & Healy",
  }),
  definePrompt({
    id: "culture-grammy-categories",
    pack: "culture",
    category: "Awards",
    promptText: "Award categories at the 2025 GRAMMYs",
    unitLabel: "categories",
    unitShort: "categories",
    answerNumeric: 94,
    difficulty: 2,
    answerYear: 2025,
    sourceLabel: "GRAMMY",
  }),
  definePrompt({
    id: "culture-harry-potter-books",
    pack: "culture",
    category: "Books",
    promptText: "Books in the main Harry Potter series",
    unitLabel: "books",
    unitShort: "books",
    answerNumeric: 7,
    difficulty: 1,
    sourceLabel: "Scholastic",
  }),
];

export const naturePrompts: Prompt[] = [
  definePrompt({
    id: "nature-earth-ocean-coverage",
    pack: "nature",
    category: "Ocean",
    promptText: "Percent of Earth's surface covered by ocean",
    unitLabel: "percent",
    unitShort: "%",
    answerNumeric: 71,
    answerDisplay: "71%",
    difficulty: 1,
    sourceLabel: "NOAA",
  }),
  definePrompt({
    id: "nature-atmosphere-layers",
    pack: "nature",
    category: "Weather",
    promptText: "Main layers of Earth's atmosphere",
    unitLabel: "layers",
    unitShort: "layers",
    answerNumeric: 5,
    difficulty: 1,
    sourceLabel: "NOAA",
  }),
  definePrompt({
    id: "nature-cloud-genera",
    pack: "nature",
    category: "Weather",
    promptText: "Official cloud genera recognized by the World Meteorological Organization",
    unitLabel: "genera",
    unitShort: "genera",
    answerNumeric: 10,
    difficulty: 2,
    sourceLabel: "World Meteorological Organization",
  }),
  definePrompt({
    id: "nature-hurricane-categories",
    pack: "nature",
    category: "Weather",
    promptText: "Categories on the Saffir-Simpson hurricane wind scale",
    unitLabel: "categories",
    unitShort: "categories",
    answerNumeric: 5,
    difficulty: 1,
    sourceLabel: "NOAA",
  }),
  definePrompt({
    id: "nature-ef-scale-ratings",
    pack: "nature",
    category: "Weather",
    promptText: "Ratings on the Enhanced Fujita tornado scale",
    unitLabel: "ratings",
    unitShort: "ratings",
    answerNumeric: 6,
    difficulty: 2,
    sourceLabel: "National Weather Service",
  }),
  definePrompt({
    id: "nature-challenger-deep-depth",
    pack: "nature",
    category: "Ocean",
    promptText: "Depth of Challenger Deep",
    unitLabel: "meters",
    unitShort: "m",
    answerNumeric: 10_935,
    difficulty: 3,
    sourceLabel: "NOAA",
  }),
  definePrompt({
    id: "nature-ocean-average-depth",
    pack: "nature",
    category: "Ocean",
    promptText: "Average depth of the ocean",
    unitLabel: "meters",
    unitShort: "m",
    answerNumeric: 3_682,
    difficulty: 3,
    sourceLabel: "NOAA",
  }),
  definePrompt({
    id: "nature-asian-elephant-gestation",
    pack: "nature",
    category: "Animals",
    promptText: "Gestation period of an Asian elephant",
    unitLabel: "months",
    unitShort: "months",
    answerNumeric: 22,
    difficulty: 2,
    sourceLabel: "Smithsonian's National Zoo",
  }),
  definePrompt({
    id: "nature-giraffe-max-height",
    pack: "nature",
    category: "Animals",
    promptText: "Maximum height of an adult male giraffe",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 18,
    difficulty: 2,
    sourceLabel: "Smithsonian's National Zoo",
  }),
  definePrompt({
    id: "nature-brown-pelican-wingspan",
    pack: "nature",
    category: "Animals",
    promptText: "Maximum wingspan of a brown pelican",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 6.5,
    difficulty: 2,
    sourceLabel: "Smithsonian's National Zoo",
  }),
];

export const transportationPrompts: Prompt[] = [
  definePrompt({
    id: "transport-channel-tunnel-length",
    pack: "transportation",
    category: "Tunnel",
    promptText: "Length of the Channel Tunnel",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 50.45,
    difficulty: 2,
    sourceLabel: "Getlink",
  }),
  definePrompt({
    id: "transport-channel-tunnel-undersea-length",
    pack: "transportation",
    category: "Tunnel",
    promptText: "Length of the undersea section of the Channel Tunnel",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 37.9,
    difficulty: 3,
    sourceLabel: "Getlink",
  }),
  definePrompt({
    id: "transport-panama-canal-lock-chambers",
    pack: "transportation",
    category: "Canal",
    promptText: "Lock chambers in the pre-expansion Panama Canal",
    unitLabel: "lock chambers",
    unitShort: "chambers",
    answerNumeric: 12,
    difficulty: 2,
    sourceLabel: "Panama Canal Authority",
  }),
  definePrompt({
    id: "transport-standard-gauge-width",
    pack: "transportation",
    category: "Rail",
    promptText: "Width of standard-gauge railway track",
    unitLabel: "millimeters",
    unitShort: "mm",
    answerNumeric: 1_435,
    difficulty: 2,
    sourceLabel: "Federal Railroad Administration",
  }),
  definePrompt({
    id: "transport-a380-length",
    pack: "transportation",
    category: "Aircraft",
    promptText: "Length of an Airbus A380",
    unitLabel: "meters",
    unitShort: "m",
    answerNumeric: 72.72,
    difficulty: 2,
    sourceLabel: "Airbus",
  }),
  definePrompt({
    id: "transport-a380-wingspan",
    pack: "transportation",
    category: "Aircraft",
    promptText: "Wingspan of an Airbus A380",
    unitLabel: "meters",
    unitShort: "m",
    answerNumeric: 79.75,
    difficulty: 2,
    sourceLabel: "Airbus",
  }),
  definePrompt({
    id: "transport-747-8-length",
    pack: "transportation",
    category: "Aircraft",
    promptText: "Length of a Boeing 747-8",
    unitLabel: "meters",
    unitShort: "m",
    answerNumeric: 76.3,
    difficulty: 2,
    sourceLabel: "Boeing",
  }),
  definePrompt({
    id: "transport-747-8-wingspan",
    pack: "transportation",
    category: "Aircraft",
    promptText: "Wingspan of a Boeing 747-8",
    unitLabel: "meters",
    unitShort: "m",
    answerNumeric: 68.4,
    difficulty: 2,
    sourceLabel: "Boeing",
  }),
  definePrompt({
    id: "transport-golden-gate-tower-height",
    pack: "transportation",
    category: "Bridge",
    promptText: "Height of the Golden Gate Bridge towers",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 746,
    difficulty: 2,
    sourceLabel: "Golden Gate Bridge Highway and Transportation District",
  }),
  definePrompt({
    id: "transport-akashi-main-span",
    pack: "transportation",
    category: "Bridge",
    promptText: "Main span of the Akashi Kaikyo Bridge",
    unitLabel: "meters",
    unitShort: "m",
    answerNumeric: 1_991,
    difficulty: 3,
    sourceLabel: "Honshu-Shikoku Bridge Expressway Company",
  }),
];

export const bodyPrompts: Prompt[] = [
  definePrompt({
    id: "body-adult-teeth",
    pack: "body",
    category: "Anatomy",
    promptText: "Teeth in an adult human mouth",
    unitLabel: "teeth",
    unitShort: "teeth",
    answerNumeric: 32,
    difficulty: 1,
    sourceLabel: "Cleveland Clinic",
  }),
  definePrompt({
    id: "body-baby-teeth",
    pack: "body",
    category: "Anatomy",
    promptText: "Baby teeth in a full primary set",
    unitLabel: "teeth",
    unitShort: "teeth",
    answerNumeric: 20,
    difficulty: 1,
    sourceLabel: "Cleveland Clinic",
  }),
  definePrompt({
    id: "body-ribs",
    pack: "body",
    category: "Anatomy",
    promptText: "Ribs in an adult human body",
    unitLabel: "ribs",
    unitShort: "ribs",
    answerNumeric: 24,
    difficulty: 1,
    sourceLabel: "Cleveland Clinic",
  }),
  definePrompt({
    id: "body-vertebrae",
    pack: "body",
    category: "Anatomy",
    promptText: "Vertebrae in the human spine",
    unitLabel: "vertebrae",
    unitShort: "vertebrae",
    answerNumeric: 33,
    difficulty: 2,
    sourceLabel: "Cleveland Clinic",
  }),
  definePrompt({
    id: "body-chromosomes",
    pack: "body",
    category: "Genetics",
    promptText: "Chromosomes in a typical human cell",
    unitLabel: "chromosomes",
    unitShort: "chromosomes",
    answerNumeric: 46,
    difficulty: 1,
    sourceLabel: "MedlinePlus",
  }),
  definePrompt({
    id: "body-heart-chambers",
    pack: "body",
    category: "Anatomy",
    promptText: "Chambers in the human heart",
    unitLabel: "chambers",
    unitShort: "chambers",
    answerNumeric: 4,
    difficulty: 1,
    sourceLabel: "Cleveland Clinic",
  }),
  definePrompt({
    id: "body-lung-lobes",
    pack: "body",
    category: "Anatomy",
    promptText: "Lobes in the human lungs",
    unitLabel: "lobes",
    unitShort: "lobes",
    answerNumeric: 5,
    difficulty: 1,
    sourceLabel: "Cleveland Clinic",
  }),
  definePrompt({
    id: "body-pregnancy-weeks",
    pack: "body",
    category: "Pregnancy",
    promptText: "Weeks in a full-term pregnancy",
    unitLabel: "weeks",
    unitShort: "weeks",
    answerNumeric: 40,
    difficulty: 1,
    sourceLabel: "MedlinePlus",
  }),
  definePrompt({
    id: "body-blood-liters",
    pack: "body",
    category: "Health",
    promptText: "Liters of blood in the average adult body",
    unitLabel: "liters",
    unitShort: "L",
    answerNumeric: 5,
    difficulty: 2,
    sourceLabel: "Cleveland Clinic",
  }),
  definePrompt({
    id: "body-temperature",
    pack: "body",
    category: "Health",
    promptText: "Average normal human body temperature",
    unitLabel: "degrees Fahrenheit",
    unitShort: "deg F",
    answerNumeric: 98.6,
    difficulty: 1,
    sourceLabel: "Cleveland Clinic",
  }),
];

export const everydayPrompts: Prompt[] = [
  definePrompt({
    id: "everyday-gallon-fluid-ounces",
    pack: "everyday",
    category: "Kitchen",
    promptText: "Fluid ounces in a US gallon",
    unitLabel: "fluid ounces",
    unitShort: "fl oz",
    answerNumeric: 128,
    difficulty: 1,
    sourceLabel: "NIST",
  }),
  definePrompt({
    id: "everyday-tablespoon-milliliters",
    pack: "everyday",
    category: "Kitchen",
    promptText: "Milliliters in a tablespoon",
    unitLabel: "milliliters",
    unitShort: "mL",
    answerNumeric: 15,
    difficulty: 1,
    sourceLabel: "NIST",
  }),
  definePrompt({
    id: "everyday-cup-tablespoons",
    pack: "everyday",
    category: "Kitchen",
    promptText: "Tablespoons in a US cup",
    unitLabel: "tablespoons",
    unitShort: "tbsp",
    answerNumeric: 16,
    difficulty: 1,
    sourceLabel: "NIST",
  }),
  definePrompt({
    id: "everyday-tablespoon-teaspoons",
    pack: "everyday",
    category: "Kitchen",
    promptText: "Teaspoons in a tablespoon",
    unitLabel: "teaspoons",
    unitShort: "tsp",
    answerNumeric: 3,
    difficulty: 1,
    sourceLabel: "NIST",
  }),
  definePrompt({
    id: "everyday-cup-fluid-ounces",
    pack: "everyday",
    category: "Kitchen",
    promptText: "Fluid ounces in a US cup",
    unitLabel: "fluid ounces",
    unitShort: "fl oz",
    answerNumeric: 8,
    difficulty: 1,
    sourceLabel: "NIST",
  }),
  definePrompt({
    id: "everyday-quart-cups",
    pack: "everyday",
    category: "Kitchen",
    promptText: "Cups in a US quart",
    unitLabel: "cups",
    unitShort: "cups",
    answerNumeric: 4,
    difficulty: 1,
    sourceLabel: "NIST",
  }),
  definePrompt({
    id: "everyday-wine-bottle-milliliters",
    pack: "everyday",
    category: "Food & Drink",
    promptText: "Milliliters in a standard wine bottle",
    unitLabel: "milliliters",
    unitShort: "mL",
    answerNumeric: 750,
    difficulty: 1,
    sourceLabel: "TTB",
  }),
  definePrompt({
    id: "everyday-soda-can-fluid-ounces",
    pack: "everyday",
    category: "Food & Drink",
    promptText: "Fluid ounces in a standard US soda can",
    unitLabel: "fluid ounces",
    unitShort: "fl oz",
    answerNumeric: 12,
    difficulty: 1,
    sourceLabel: "Coca-Cola",
  }),
  definePrompt({
    id: "everyday-coke-caffeine",
    pack: "everyday",
    category: "Food & Drink",
    promptText: "Caffeine in a 12-ounce can of Coca-Cola",
    unitLabel: "milligrams",
    unitShort: "mg",
    answerNumeric: 34,
    difficulty: 2,
    sourceLabel: "Coca-Cola",
  }),
  definePrompt({
    id: "everyday-fat-calories",
    pack: "everyday",
    category: "Nutrition",
    promptText: "Calories in one gram of fat",
    unitLabel: "calories",
    unitShort: "cal",
    answerNumeric: 9,
    difficulty: 1,
    sourceLabel: "FDA",
  }),
];
