import { formatNumericValue, formatPromptNumericValue } from "./format";
import { otherPrompts } from "./other-prompts";
import { validatePromptBank } from "./prompt-validation.js";
import type { Prompt } from "../../types/game";

type PromptInput = Omit<Prompt, "answerDisplay"> & {
  answerDisplay?: string;
};

function formatAnswerDisplay(input: PromptInput) {
  return formatPromptNumericValue(input.answerNumeric, input);
}

function definePrompt(input: PromptInput): Prompt {
  return {
    ...input,
    answerDisplay: input.answerDisplay ?? formatAnswerDisplay(input),
  };
}

function defineUsdPrompt(input: Omit<PromptInput, "answerDisplay" | "unitLabel" | "unitShort">): Prompt {
  return definePrompt({
    ...input,
    unitLabel: "US dollars",
    unitShort: "USD",
    answerDisplay: `$${formatNumericValue(input.answerNumeric)}`,
  });
}

const geographyPrompts: Prompt[] = [
  definePrompt({
    id: "geo-mongolia-pop",
    pack: "geography",
    category: "Population",
    promptText: "Population of Mongolia",
    unitLabel: "people",
    unitShort: "people",
    answerNumeric: 3_504_741,
    hintText: "Use the 2024 estimate.",
    difficulty: 2,
    answerYear: 2024,
    sourceLabel: "National Statistical Office of Mongolia",
  }),
  definePrompt({
    id: "geo-nevada-area",
    pack: "geography",
    category: "Land area",
    promptText: "Land area of Nevada",
    unitLabel: "square miles",
    unitShort: "sq mi",
    answerNumeric: 110_572,
    hintText: "Only the land area, not the total area.",
    difficulty: 2,
    sourceLabel: "U.S. Census Bureau",
  }),
  definePrompt({
    id: "geo-danube-length",
    pack: "geography",
    category: "Length",
    promptText: "Length of the Danube River",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 2_850,
    difficulty: 2,
    sourceLabel: "ICPDR",
  }),
  definePrompt({
    id: "geo-africa-countries",
    pack: "geography",
    category: "Count",
    promptText: "Number of countries in Africa",
    unitLabel: "countries",
    unitShort: "countries",
    answerNumeric: 54,
    difficulty: 1,
    sourceLabel: "United Nations",
  }),
  definePrompt({
    id: "geo-iceland-pop",
    pack: "geography",
    category: "Population",
    promptText: "Population of Iceland",
    unitLabel: "people",
    unitShort: "people",
    answerNumeric: 383_726,
    hintText: "Use the January 1, 2024 population figure.",
    difficulty: 2,
    answerYear: 2024,
    sourceLabel: "Statistics Iceland",
  }),
  definePrompt({
    id: "geo-ireland-pop",
    pack: "geography",
    category: "Population",
    promptText: "Population of Ireland",
    unitLabel: "people",
    unitShort: "people",
    answerNumeric: 5_380_300,
    hintText: "Use the April 2024 estimate.",
    difficulty: 2,
    answerYear: 2024,
    sourceLabel: "CSO Ireland",
  }),
  definePrompt({
    id: "geo-australia-pop",
    pack: "geography",
    category: "Population",
    promptText: "Population of Australia",
    unitLabel: "people",
    unitShort: "people",
    answerNumeric: 27_200_000,
    hintText: "Use the June 2024 estimate.",
    difficulty: 2,
    answerYear: 2024,
    sourceLabel: "ABS",
  }),
  definePrompt({
    id: "geo-nile-length",
    pack: "geography",
    category: "Length",
    promptText: "Length of the Nile River",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 6_650,
    difficulty: 2,
    sourceLabel: "Encyclopaedia Britannica",
  }),
  definePrompt({
    id: "geo-suez-canal-length",
    pack: "geography",
    category: "Length",
    promptText: "Length of the Suez Canal",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 193,
    difficulty: 2,
    sourceLabel: "Suez Canal Authority",
  }),
  definePrompt({
    id: "geo-rhine-length",
    pack: "geography",
    category: "Length",
    promptText: "Length of the Rhine River",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 1_230,
    difficulty: 2,
    sourceLabel: "Encyclopaedia Britannica",
  }),
  definePrompt({
    id: "geo-angel-falls-height",
    pack: "geography",
    category: "Height",
    promptText: "Height of Angel Falls",
    unitLabel: "meters",
    unitShort: "m",
    answerNumeric: 979,
    difficulty: 2,
    sourceLabel: "UNESCO",
  }),
  definePrompt({
    id: "geo-lake-baikal-depth",
    pack: "geography",
    category: "Depth",
    promptText: "Maximum depth of Lake Baikal",
    unitLabel: "meters",
    unitShort: "m",
    answerNumeric: 1_642,
    difficulty: 2,
    sourceLabel: "UNESCO",
  }),
  definePrompt({
    id: "geo-elbrus-height",
    pack: "geography",
    category: "Height",
    promptText: "Height of Mount Elbrus",
    unitLabel: "meters",
    unitShort: "m",
    answerNumeric: 5_642,
    difficulty: 2,
    sourceLabel: "Encyclopaedia Britannica",
  }),
  definePrompt({
    id: "geo-south-america-countries",
    pack: "geography",
    category: "Count",
    promptText: "Number of sovereign states in South America",
    unitLabel: "countries",
    unitShort: "countries",
    answerNumeric: 12,
    hintText: "Count sovereign states only.",
    difficulty: 1,
    sourceLabel: "United Nations",
  }),
  definePrompt({
    id: "geo-russia-time-zones",
    pack: "geography",
    category: "Count",
    promptText: "Number of time zones in Russia",
    unitLabel: "time zones",
    unitShort: "zones",
    answerNumeric: 11,
    difficulty: 1,
    sourceLabel: "Encyclopaedia Britannica",
  }),
  definePrompt({
    id: "geo-danube-countries",
    pack: "geography",
    category: "Count",
    promptText: "Number of countries the Danube flows through",
    unitLabel: "countries",
    unitShort: "countries",
    answerNumeric: 10,
    difficulty: 2,
    sourceLabel: "ICPDR",
  }),
  definePrompt({
    id: "geo-fuji-height",
    pack: "geography",
    category: "Height",
    promptText: "Height of Mount Fuji",
    unitLabel: "meters",
    unitShort: "m",
    answerNumeric: 3_776,
    difficulty: 2,
    sourceLabel: "JNTO",
  }),
  definePrompt({
    id: "geo-eu-members",
    pack: "geography",
    category: "Count",
    promptText: "Member countries in the European Union",
    unitLabel: "countries",
    unitShort: "countries",
    answerNumeric: 27,
    difficulty: 1,
    sourceLabel: "European Union",
  }),
  definePrompt({
    id: "geo-canada-provinces-territories",
    pack: "geography",
    category: "Count",
    promptText: "Provinces and territories in Canada",
    unitLabel: "provinces and territories",
    unitShort: "regions",
    answerNumeric: 13,
    difficulty: 1,
    sourceLabel: "Government of Canada",
  }),
  definePrompt({
    id: "geo-greece-islands",
    pack: "geography",
    category: "Count",
    promptText: "Islands, islets, and rocky islets in Greece",
    unitLabel: "islands",
    unitShort: "islands",
    answerNumeric: 6_000,
    difficulty: 3,
    sourceLabel: "Visit Greece",
  }),
  definePrompt({
    id: "geo-commonwealth-members",
    pack: "geography",
    category: "Count",
    promptText: "Member countries in the Commonwealth",
    unitLabel: "countries",
    unitShort: "countries",
    answerNumeric: 56,
    difficulty: 2,
    sourceLabel: "The Commonwealth",
  }),
  definePrompt({
    id: "geo-switzerland-languages",
    pack: "geography",
    category: "Count",
    promptText: "National languages of Switzerland",
    unitLabel: "languages",
    unitShort: "languages",
    answerNumeric: 4,
    difficulty: 1,
    sourceLabel: "Swiss Confederation",
  }),
];

const techPrompts: Prompt[] = [
  defineUsdPrompt({
    id: "tech-iphone-price",
    pack: "tech",
    category: "Launch price",
    promptText: "Starting US price of the original iPhone",
    answerNumeric: 499,
    hintText: "Base model at launch in 2007.",
    difficulty: 1,
    answerYear: 2007,
    sourceLabel: "Apple",
  }),
  definePrompt({
    id: "tech-tweet-limit",
    pack: "tech",
    category: "Platform limit",
    promptText: "Character limit of a classic tweet before 2017",
    unitLabel: "characters",
    unitShort: "chars",
    answerNumeric: 140,
    answerYear: 2016,
    difficulty: 1,
    sourceLabel: "X",
  }),
  definePrompt({
    id: "tech-gigabyte-bytes",
    pack: "tech",
    category: "Storage",
    promptText: "Bytes in one decimal gigabyte",
    unitLabel: "bytes",
    unitShort: "bytes",
    answerNumeric: 1_000_000_000,
    difficulty: 2,
    sourceLabel: "NIST",
  }),
  definePrompt({
    id: "tech-jpeg-year",
    pack: "tech",
    category: "Year",
    promptText: "Year the JPEG standard was first published",
    unitLabel: "year",
    unitShort: "year",
    answerNumeric: 1992,
    difficulty: 2,
    answerYear: 1992,
    sourceLabel: "JPEG Committee",
  }),
  defineUsdPrompt({
    id: "tech-ipad-price",
    pack: "tech",
    category: "Launch price",
    promptText: "Starting US price of the original iPad",
    answerNumeric: 499,
    hintText: "Base model at launch in 2010.",
    difficulty: 1,
    answerYear: 2010,
    sourceLabel: "Apple",
  }),
  defineUsdPrompt({
    id: "tech-apple-watch-price",
    pack: "tech",
    category: "Launch price",
    promptText: "Starting US price of the first Apple Watch",
    answerNumeric: 349,
    hintText: "Sport model at launch in 2015.",
    difficulty: 1,
    answerYear: 2015,
    sourceLabel: "Apple",
  }),
  defineUsdPrompt({
    id: "tech-switch-price",
    pack: "tech",
    category: "Launch price",
    promptText: "Starting US price of the original Nintendo Switch",
    answerNumeric: 299,
    hintText: "Base console at launch in 2017.",
    difficulty: 1,
    answerYear: 2017,
    sourceLabel: "Nintendo",
  }),
  definePrompt({
    id: "tech-sms-limit",
    pack: "tech",
    category: "Platform limit",
    promptText: "Character limit of a standard SMS",
    unitLabel: "characters",
    unitShort: "chars",
    answerNumeric: 160,
    difficulty: 1,
    sourceLabel: "GSMA",
  }),
  definePrompt({
    id: "tech-ipv6-bits",
    pack: "tech",
    category: "Protocol",
    promptText: "Bits in an IPv6 address",
    unitLabel: "bits",
    unitShort: "bits",
    answerNumeric: 128,
    difficulty: 1,
    sourceLabel: "IETF",
  }),
  definePrompt({
    id: "tech-mac-address-bits",
    pack: "tech",
    category: "Protocol",
    promptText: "Bits in a standard MAC address",
    unitLabel: "bits",
    unitShort: "bits",
    answerNumeric: 48,
    difficulty: 1,
    sourceLabel: "IEEE",
  }),
  definePrompt({
    id: "tech-highest-port",
    pack: "tech",
    category: "Platform limit",
    promptText: "Highest valid TCP or UDP port number",
    unitLabel: "port number",
    unitShort: "port",
    answerNumeric: 65_535,
    difficulty: 2,
    sourceLabel: "IANA",
  }),
  definePrompt({
    id: "tech-dns-label-limit",
    pack: "tech",
    category: "Platform limit",
    promptText: "Maximum length of one DNS label",
    unitLabel: "characters",
    unitShort: "chars",
    answerNumeric: 63,
    difficulty: 2,
    sourceLabel: "IETF",
  }),
  definePrompt({
    id: "tech-qr-year",
    pack: "tech",
    category: "Year",
    promptText: "Year the QR Code was invented",
    unitLabel: "year",
    unitShort: "year",
    answerNumeric: 1994,
    difficulty: 2,
    sourceLabel: "DENSO WAVE",
  }),
  definePrompt({
    id: "tech-app-store-launch-apps",
    pack: "tech",
    category: "Launch lineup",
    promptText: "Number of apps in the App Store at launch",
    unitLabel: "apps",
    unitShort: "apps",
    answerNumeric: 500,
    hintText: "Use the July 2008 launch lineup.",
    difficulty: 2,
    answerYear: 2008,
    sourceLabel: "Apple",
  }),
  definePrompt({
    id: "tech-terabyte-bytes",
    pack: "tech",
    category: "Storage",
    promptText: "Bytes in one decimal terabyte",
    unitLabel: "bytes",
    unitShort: "bytes",
    answerNumeric: 1_000_000_000_000,
    difficulty: 2,
    sourceLabel: "NIST",
  }),
  definePrompt({
    id: "tech-4k-width",
    pack: "tech",
    category: "Display",
    promptText: "Horizontal pixels in 4K UHD",
    unitLabel: "pixels",
    unitShort: "px",
    answerNumeric: 3_840,
    difficulty: 1,
    sourceLabel: "Consumer Technology Association",
  }),
  defineUsdPrompt({
    id: "tech-ipod-price",
    pack: "tech",
    category: "Launch price",
    promptText: "Starting US price of the original iPod",
    answerNumeric: 399,
    hintText: "Base model at launch in 2001.",
    difficulty: 1,
    answerYear: 2001,
    sourceLabel: "Apple",
  }),
  defineUsdPrompt({
    id: "tech-macbook-air-price",
    pack: "tech",
    category: "Launch price",
    promptText: "Starting US price of the original MacBook Air",
    answerNumeric: 1_799,
    hintText: "Base model at launch in 2008.",
    difficulty: 2,
    answerYear: 2008,
    sourceLabel: "Apple",
  }),
  definePrompt({
    id: "tech-html5-year",
    pack: "tech",
    category: "Year",
    promptText: "Year the first public working draft of HTML5 was published",
    unitLabel: "year",
    unitShort: "year",
    answerNumeric: 2008,
    difficulty: 2,
    answerYear: 2008,
    sourceLabel: "W3C",
  }),
  definePrompt({
    id: "tech-bluetooth-sig-year",
    pack: "tech",
    category: "Year",
    promptText: "Year the Bluetooth SIG was founded",
    unitLabel: "year",
    unitShort: "year",
    answerNumeric: 1998,
    difficulty: 2,
    answerYear: 1998,
    sourceLabel: "Bluetooth SIG",
  }),
  definePrompt({
    id: "tech-uuid-bits",
    pack: "tech",
    category: "Protocol",
    promptText: "Bits in a UUID",
    unitLabel: "bits",
    unitShort: "bits",
    answerNumeric: 128,
    difficulty: 1,
    sourceLabel: "IETF",
  }),
  definePrompt({
    id: "tech-unicode-codespace",
    pack: "tech",
    category: "Standard",
    promptText: "Possible code points in the Unicode codespace",
    unitLabel: "code points",
    unitShort: "code points",
    answerNumeric: 1_114_112,
    difficulty: 3,
    sourceLabel: "Unicode",
  }),
  definePrompt({
    id: "tech-dynamic-port-start",
    pack: "tech",
    category: "Protocol",
    promptText: "First dynamic or private TCP/UDP port number",
    unitLabel: "port number",
    unitShort: "port",
    answerNumeric: 49_152,
    difficulty: 2,
    sourceLabel: "IANA",
  }),
];

const usPrompts: Prompt[] = [
  definePrompt({
    id: "us-electoral-votes",
    pack: "us",
    category: "Civics",
    promptText: "Electoral votes needed to win a US presidential election",
    unitLabel: "electoral votes",
    unitShort: "votes",
    answerNumeric: 270,
    difficulty: 1,
    sourceLabel: "National Archives",
  }),
  definePrompt({
    id: "us-route-66",
    pack: "us",
    category: "Distance",
    promptText: "Historic length of Route 66",
    unitLabel: "miles",
    unitShort: "mi",
    answerNumeric: 2_448,
    difficulty: 2,
    sourceLabel: "National Park Service",
  }),
  definePrompt({
    id: "us-national-parks",
    pack: "us",
    category: "Count",
    promptText: "Number of US national parks",
    unitLabel: "parks",
    unitShort: "parks",
    answerNumeric: 63,
    difficulty: 1,
    sourceLabel: "National Park Service",
  }),
  definePrompt({
    id: "us-statue-liberty",
    pack: "us",
    category: "Height",
    promptText: "Height of the Statue of Liberty from ground to torch",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 305,
    difficulty: 2,
    sourceLabel: "National Park Service",
  }),
  definePrompt({
    id: "us-house-members",
    pack: "us",
    category: "Civics",
    promptText: "Voting members in the US House of Representatives",
    unitLabel: "members",
    unitShort: "members",
    answerNumeric: 435,
    difficulty: 1,
    sourceLabel: "House.gov",
  }),
  definePrompt({
    id: "us-supreme-court-justices",
    pack: "us",
    category: "Civics",
    promptText: "Justices on the US Supreme Court",
    unitLabel: "justices",
    unitShort: "justices",
    answerNumeric: 9,
    difficulty: 1,
    sourceLabel: "SupremeCourt.gov",
  }),
  definePrompt({
    id: "us-senate-min-age",
    pack: "us",
    category: "Civics",
    promptText: "Minimum age to serve in the US Senate",
    unitLabel: "years",
    unitShort: "years",
    answerNumeric: 30,
    difficulty: 1,
    sourceLabel: "Senate.gov",
  }),
  definePrompt({
    id: "us-gateway-arch-height",
    pack: "us",
    category: "Height",
    promptText: "Height of the Gateway Arch",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 630,
    difficulty: 2,
    sourceLabel: "National Park Service",
  }),
  definePrompt({
    id: "us-washington-monument-height",
    pack: "us",
    category: "Height",
    promptText: "Height of the Washington Monument",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 555,
    difficulty: 2,
    sourceLabel: "National Park Service",
  }),
  definePrompt({
    id: "us-hoover-dam-height",
    pack: "us",
    category: "Height",
    promptText: "Height of Hoover Dam",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 726,
    difficulty: 2,
    sourceLabel: "Bureau of Reclamation",
  }),
  definePrompt({
    id: "us-mexico-border-states",
    pack: "us",
    category: "Count",
    promptText: "States that border Mexico",
    unitLabel: "states",
    unitShort: "states",
    answerNumeric: 4,
    difficulty: 1,
    sourceLabel: "Encyclopaedia Britannica",
  }),
  definePrompt({
    id: "us-gulf-states",
    pack: "us",
    category: "Count",
    promptText: "States that touch the Gulf of Mexico",
    unitLabel: "states",
    unitShort: "states",
    answerNumeric: 5,
    difficulty: 1,
    sourceLabel: "NOAA",
  }),
  definePrompt({
    id: "us-texas-counties",
    pack: "us",
    category: "Count",
    promptText: "Counties in Texas",
    unitLabel: "counties",
    unitShort: "counties",
    answerNumeric: 254,
    difficulty: 2,
    sourceLabel: "Texas State Library",
  }),
  definePrompt({
    id: "us-empire-state-floors",
    pack: "us",
    category: "Building",
    promptText: "Floors in the Empire State Building",
    unitLabel: "floors",
    unitShort: "floors",
    answerNumeric: 102,
    difficulty: 1,
    sourceLabel: "Empire State Building",
  }),
  definePrompt({
    id: "us-rushmore-face-height",
    pack: "us",
    category: "Landmark",
    promptText: "Height of each Mount Rushmore face",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 60,
    difficulty: 2,
    sourceLabel: "National Park Service",
  }),
  definePrompt({
    id: "us-golden-gate-main-span",
    pack: "us",
    category: "Bridge",
    promptText: "Main span of the Golden Gate Bridge",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 4_200,
    hintText: "Use the main span only, not the full bridge length.",
    difficulty: 2,
    sourceLabel: "Golden Gate Bridge Highway and Transportation District",
  }),
  definePrompt({
    id: "us-electoral-college-members",
    pack: "us",
    category: "Civics",
    promptText: "Members of the Electoral College",
    unitLabel: "electors",
    unitShort: "electors",
    answerNumeric: 538,
    difficulty: 1,
    sourceLabel: "National Archives",
  }),
  definePrompt({
    id: "us-constitutional-amendments",
    pack: "us",
    category: "Civics",
    promptText: "Amendments to the US Constitution",
    unitLabel: "amendments",
    unitShort: "amendments",
    answerNumeric: 27,
    difficulty: 1,
    sourceLabel: "National Archives",
  }),
  definePrompt({
    id: "us-one-world-height",
    pack: "us",
    category: "Height",
    promptText: "Architectural height of One World Trade Center",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 1_776,
    difficulty: 2,
    sourceLabel: "One World Observatory",
  }),
  definePrompt({
    id: "us-space-needle-height",
    pack: "us",
    category: "Height",
    promptText: "Height of the Space Needle",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 605,
    difficulty: 2,
    sourceLabel: "Space Needle",
  }),
  definePrompt({
    id: "us-mount-whitney-height",
    pack: "us",
    category: "Height",
    promptText: "Elevation of Mount Whitney",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 14_505,
    difficulty: 2,
    sourceLabel: "National Park Service",
  }),
  definePrompt({
    id: "us-cbbt-length",
    pack: "us",
    category: "Bridge",
    promptText: "Length of the Chesapeake Bay Bridge-Tunnel",
    unitLabel: "miles",
    unitShort: "mi",
    answerNumeric: 17.6,
    difficulty: 2,
    sourceLabel: "Chesapeake Bay Bridge-Tunnel",
  }),
];

const spacePrompts: Prompt[] = [
  definePrompt({
    id: "space-mercury-diameter",
    pack: "space",
    category: "Diameter",
    promptText: "Diameter of Mercury",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 4_879,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-venus-diameter",
    pack: "space",
    category: "Diameter",
    promptText: "Diameter of Venus",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 12_104,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-earth-diameter",
    pack: "space",
    category: "Diameter",
    promptText: "Diameter of Earth",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 12_756,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-moon-diameter",
    pack: "space",
    category: "Diameter",
    promptText: "Diameter of the Moon",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 3_475,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-mars-diameter",
    pack: "space",
    category: "Diameter",
    promptText: "Diameter of Mars",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 6_779,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-jupiter-diameter",
    pack: "space",
    category: "Diameter",
    promptText: "Diameter of Jupiter",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 139_820,
    difficulty: 3,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-saturn-diameter",
    pack: "space",
    category: "Diameter",
    promptText: "Diameter of Saturn",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 116_460,
    difficulty: 3,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-uranus-diameter",
    pack: "space",
    category: "Diameter",
    promptText: "Diameter of Uranus",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 50_724,
    difficulty: 3,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-neptune-diameter",
    pack: "space",
    category: "Diameter",
    promptText: "Diameter of Neptune",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 49_244,
    difficulty: 3,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-mercury-year",
    pack: "space",
    category: "Orbit",
    promptText: "Length of a year on Mercury",
    unitLabel: "Earth days",
    unitShort: "days",
    answerNumeric: 88,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-venus-day",
    pack: "space",
    category: "Rotation",
    promptText: "Length of a day on Venus",
    unitLabel: "Earth days",
    unitShort: "days",
    answerNumeric: 243,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-mars-day",
    pack: "space",
    category: "Rotation",
    promptText: "Length of a day on Mars",
    unitLabel: "hours",
    unitShort: "hours",
    answerNumeric: 24.6,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-mars-year",
    pack: "space",
    category: "Orbit",
    promptText: "Length of a year on Mars",
    unitLabel: "Earth days",
    unitShort: "days",
    answerNumeric: 687,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-earth-sun-distance",
    pack: "space",
    category: "Distance",
    promptText: "Average distance from Earth to the Sun",
    unitLabel: "miles",
    unitShort: "mi",
    answerNumeric: 93_000_000,
    difficulty: 3,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-iss-altitude",
    pack: "space",
    category: "Altitude",
    promptText: "Average altitude of the International Space Station",
    unitLabel: "miles",
    unitShort: "mi",
    answerNumeric: 250,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-iss-speed",
    pack: "space",
    category: "Speed",
    promptText: "Orbital speed of the International Space Station",
    unitLabel: "miles per hour",
    unitShort: "mph",
    answerNumeric: 17_500,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-sun-age",
    pack: "space",
    category: "Age",
    promptText: "Age of the Sun",
    unitLabel: "billion years",
    unitShort: "bn years",
    answerNumeric: 4.6,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "space-saturn-rings",
    pack: "space",
    category: "Count",
    promptText: "Main rings of Saturn",
    unitLabel: "rings",
    unitShort: "rings",
    answerNumeric: 7,
    difficulty: 1,
    sourceLabel: "NASA",
  }),
];

const sportsPrompts: Prompt[] = [
  definePrompt({
    id: "sports-nba-free-throw-line",
    pack: "sports",
    category: "Basketball",
    promptText: "Distance from the backboard to the NBA free-throw line",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 15,
    difficulty: 1,
    sourceLabel: "NBA",
  }),
  definePrompt({
    id: "sports-nba-three-point-top",
    pack: "sports",
    category: "Basketball",
    promptText: "Distance from the basket to the NBA three-point line at the top of the arc",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 23.75,
    difficulty: 2,
    sourceLabel: "NBA",
  }),
  definePrompt({
    id: "sports-nba-rim-height",
    pack: "sports",
    category: "Basketball",
    promptText: "Height of an NBA basket rim",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 10,
    difficulty: 1,
    sourceLabel: "NBA",
  }),
  definePrompt({
    id: "sports-nba-shot-clock",
    pack: "sports",
    category: "Basketball",
    promptText: "Seconds on the NBA shot clock at the start of a possession",
    unitLabel: "seconds",
    unitShort: "sec",
    answerNumeric: 24,
    difficulty: 1,
    sourceLabel: "NBA",
  }),
  definePrompt({
    id: "sports-mlb-basepaths",
    pack: "sports",
    category: "Baseball",
    promptText: "Distance between bases in Major League Baseball",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 90,
    difficulty: 1,
    sourceLabel: "MLB",
  }),
  definePrompt({
    id: "sports-mlb-pitching-distance",
    pack: "sports",
    category: "Baseball",
    promptText: "Distance from the pitching rubber to home plate in Major League Baseball",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 60.5,
    difficulty: 2,
    sourceLabel: "MLB",
  }),
  definePrompt({
    id: "sports-mlb-regulation-innings",
    pack: "sports",
    category: "Baseball",
    promptText: "Innings in a regulation Major League Baseball game",
    unitLabel: "innings",
    unitShort: "innings",
    answerNumeric: 9,
    difficulty: 1,
    sourceLabel: "MLB",
  }),
  definePrompt({
    id: "sports-soccer-goal-width",
    pack: "sports",
    category: "Soccer",
    promptText: "Width of a soccer goal",
    unitLabel: "yards",
    unitShort: "yd",
    answerNumeric: 8,
    difficulty: 1,
    sourceLabel: "IFAB",
  }),
  definePrompt({
    id: "sports-soccer-goal-height",
    pack: "sports",
    category: "Soccer",
    promptText: "Height of a soccer goal",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 8,
    difficulty: 1,
    sourceLabel: "IFAB",
  }),
  definePrompt({
    id: "sports-soccer-penalty-mark",
    pack: "sports",
    category: "Soccer",
    promptText: "Distance from the goal line to the soccer penalty mark",
    unitLabel: "yards",
    unitShort: "yd",
    answerNumeric: 12,
    difficulty: 1,
    sourceLabel: "IFAB",
  }),
  definePrompt({
    id: "sports-soccer-center-circle",
    pack: "sports",
    category: "Soccer",
    promptText: "Radius of the center circle on a soccer field",
    unitLabel: "yards",
    unitShort: "yd",
    answerNumeric: 10,
    difficulty: 2,
    sourceLabel: "IFAB",
  }),
  definePrompt({
    id: "sports-golf-round-holes",
    pack: "sports",
    category: "Golf",
    promptText: "Holes in a stipulated round of golf",
    unitLabel: "holes",
    unitShort: "holes",
    answerNumeric: 18,
    difficulty: 1,
    sourceLabel: "USGA",
  }),
];

const mixedOnlyPrompts: Prompt[] = [
  definePrompt({
    id: "mix-moon-distance",
    pack: "mixed",
    category: "Distance",
    promptText: "Average distance from Earth to the Moon",
    unitLabel: "miles",
    unitShort: "mi",
    answerNumeric: 238_855,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "mix-piano-keys",
    pack: "mixed",
    category: "Count",
    promptText: "Keys on a standard modern piano",
    unitLabel: "keys",
    unitShort: "keys",
    answerNumeric: 88,
    difficulty: 1,
    sourceLabel: "Steinway",
  }),
  definePrompt({
    id: "mix-kilimanjaro-height",
    pack: "mixed",
    category: "Height",
    promptText: "Height of Mount Kilimanjaro",
    unitLabel: "meters",
    unitShort: "m",
    answerNumeric: 5_895,
    difficulty: 2,
    sourceLabel: "UNESCO",
  }),
  definePrompt({
    id: "mix-olympic-pool",
    pack: "mixed",
    category: "Volume",
    promptText: "Water held by an Olympic swimming pool",
    unitLabel: "liters",
    unitShort: "L",
    answerNumeric: 2_500_000,
    difficulty: 3,
    sourceLabel: "World Aquatics",
  }),
  definePrompt({
    id: "mix-human-bones",
    pack: "mixed",
    category: "Science",
    promptText: "Bones in an adult human body",
    unitLabel: "bones",
    unitShort: "bones",
    answerNumeric: 206,
    difficulty: 1,
    sourceLabel: "Cleveland Clinic",
  }),
  definePrompt({
    id: "mix-earth-circumference",
    pack: "mixed",
    category: "Science",
    promptText: "Earth's circumference at the equator",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 40_075,
    difficulty: 2,
    sourceLabel: "NASA",
  }),
  definePrompt({
    id: "mix-marathon-distance",
    pack: "mixed",
    category: "Sports",
    promptText: "Distance of a marathon",
    unitLabel: "miles",
    unitShort: "mi",
    answerNumeric: 26.2,
    hintText: "Use the standard race distance.",
    difficulty: 1,
    sourceLabel: "World Athletics",
  }),
  definePrompt({
    id: "mix-basketball-hoop",
    pack: "mixed",
    category: "Sports",
    promptText: "Diameter of a basketball hoop",
    unitLabel: "inches",
    unitShort: "in",
    answerNumeric: 18,
    difficulty: 1,
    sourceLabel: "NBA",
  }),
  definePrompt({
    id: "mix-standard-deck",
    pack: "mixed",
    category: "Culture",
    promptText: "Cards in a standard playing-card deck",
    unitLabel: "cards",
    unitShort: "cards",
    answerNumeric: 52,
    difficulty: 1,
    sourceLabel: "Bicycle Cards",
  }),
  definePrompt({
    id: "mix-greek-alphabet",
    pack: "mixed",
    category: "Culture",
    promptText: "Letters in the Greek alphabet",
    unitLabel: "letters",
    unitShort: "letters",
    answerNumeric: 24,
    difficulty: 1,
    sourceLabel: "Encyclopaedia Britannica",
  }),
  definePrompt({
    id: "mix-oil-barrel-liters",
    pack: "mixed",
    category: "Measurement",
    promptText: "Liters in one barrel of oil",
    unitLabel: "liters",
    unitShort: "L",
    answerNumeric: 159,
    difficulty: 2,
    sourceLabel: "U.S. Energy Information Administration",
  }),
  definePrompt({
    id: "mix-minutes-week",
    pack: "mixed",
    category: "Measurement",
    promptText: "Minutes in a week",
    unitLabel: "minutes",
    unitShort: "min",
    answerNumeric: 10_080,
    difficulty: 1,
    sourceLabel: "NIST",
  }),
  definePrompt({
    id: "mix-constellations",
    pack: "mixed",
    category: "Science",
    promptText: "Officially recognized constellations",
    unitLabel: "constellations",
    unitShort: "constellations",
    answerNumeric: 88,
    difficulty: 2,
    sourceLabel: "IAU",
  }),
  definePrompt({
    id: "mix-chemical-elements",
    pack: "mixed",
    category: "Science",
    promptText: "Named chemical elements in the periodic table",
    unitLabel: "elements",
    unitShort: "elements",
    answerNumeric: 118,
    difficulty: 1,
    sourceLabel: "IUPAC",
  }),
  definePrompt({
    id: "mix-first-oscars-year",
    pack: "mixed",
    category: "Year",
    promptText: "Year of the first Academy Awards",
    unitLabel: "year",
    unitShort: "year",
    answerNumeric: 1929,
    difficulty: 2,
    answerYear: 1929,
    sourceLabel: "Oscars",
  }),
  definePrompt({
    id: "mix-first-oscars-guests",
    pack: "mixed",
    category: "Culture",
    promptText: "Guests at the first Academy Awards",
    unitLabel: "guests",
    unitShort: "guests",
    answerNumeric: 270,
    difficulty: 2,
    answerYear: 1929,
    sourceLabel: "Oscars",
  }),
  defineUsdPrompt({
    id: "mix-first-oscars-ticket",
    pack: "mixed",
    category: "Ticket price",
    promptText: "Ticket price for the first Academy Awards",
    answerNumeric: 5,
    difficulty: 2,
    answerYear: 1929,
    sourceLabel: "Oscars",
  }),
  definePrompt({
    id: "mix-nobel-categories",
    pack: "mixed",
    category: "Culture",
    promptText: "Nobel Prize categories",
    unitLabel: "categories",
    unitShort: "categories",
    answerNumeric: 6,
    difficulty: 1,
    sourceLabel: "Nobel Prize",
  }),
];

export const PROMPTS: Prompt[] = validatePromptBank([
  ...geographyPrompts,
  ...techPrompts,
  ...usPrompts,
  ...spacePrompts,
  ...sportsPrompts,
  ...otherPrompts,
  ...mixedOnlyPrompts,
]);
