import type { Prompt } from "@/types/cwogo";

export const PROMPTS: Prompt[] = [
  {
    id: "geo-mongolia-pop",
    pack: "geography",
    category: "Population",
    promptText: "Population of Mongolia",
    unitLabel: "people",
    unitShort: "people",
    answerNumeric: 3_504_741,
    answerDisplay: "3,504,741",
    hintText: "Use the 2024 estimate.",
    difficulty: 2,
    answerYear: 2024,
  },
  {
    id: "geo-nevada-area",
    pack: "geography",
    category: "Land area",
    promptText: "Land area of Nevada",
    unitLabel: "square miles",
    unitShort: "sq mi",
    answerNumeric: 110_572,
    answerDisplay: "110,572",
    hintText: "Only the land area, not the total area.",
    difficulty: 2,
  },
  {
    id: "geo-danube-length",
    pack: "geography",
    category: "Length",
    promptText: "Length of the Danube River",
    unitLabel: "kilometers",
    unitShort: "km",
    answerNumeric: 2_850,
    answerDisplay: "2,850",
    difficulty: 2,
  },
  {
    id: "geo-africa-countries",
    pack: "geography",
    category: "Count",
    promptText: "Number of countries in Africa",
    unitLabel: "countries",
    unitShort: "countries",
    answerNumeric: 54,
    answerDisplay: "54",
    difficulty: 1,
  },
  {
    id: "tech-iphone-price",
    pack: "tech",
    category: "Launch price",
    promptText: "Starting US price of the original iPhone",
    unitLabel: "US dollars",
    unitShort: "USD",
    answerNumeric: 499,
    answerDisplay: "$499",
    hintText: "Base model at launch in 2007.",
    difficulty: 1,
    answerYear: 2007,
  },
  {
    id: "tech-tweet-limit",
    pack: "tech",
    category: "Platform limit",
    promptText: "Character limit of a classic tweet before 2017",
    unitLabel: "characters",
    unitShort: "chars",
    answerNumeric: 140,
    answerDisplay: "140",
    answerYear: 2016,
    difficulty: 1,
  },
  {
    id: "tech-gigabyte-bytes",
    pack: "tech",
    category: "Storage",
    promptText: "Bytes in one decimal gigabyte",
    unitLabel: "bytes",
    unitShort: "bytes",
    answerNumeric: 1_000_000_000,
    answerDisplay: "1,000,000,000",
    difficulty: 2,
  },
  {
    id: "tech-jpeg-year",
    pack: "tech",
    category: "Year",
    promptText: "Year the JPEG standard was first published",
    unitLabel: "year",
    unitShort: "year",
    answerNumeric: 1992,
    answerDisplay: "1992",
    difficulty: 2,
  },
  {
    id: "us-electoral-votes",
    pack: "us",
    category: "Civics",
    promptText: "Electoral votes needed to win a US presidential election",
    unitLabel: "electoral votes",
    unitShort: "votes",
    answerNumeric: 270,
    answerDisplay: "270",
    difficulty: 1,
  },
  {
    id: "us-route-66",
    pack: "us",
    category: "Distance",
    promptText: "Historic length of Route 66",
    unitLabel: "miles",
    unitShort: "mi",
    answerNumeric: 2_448,
    answerDisplay: "2,448",
    difficulty: 2,
  },
  {
    id: "us-national-parks",
    pack: "us",
    category: "Count",
    promptText: "Number of US national parks",
    unitLabel: "parks",
    unitShort: "parks",
    answerNumeric: 63,
    answerDisplay: "63",
    difficulty: 1,
  },
  {
    id: "us-statue-liberty",
    pack: "us",
    category: "Height",
    promptText: "Height of the Statue of Liberty from ground to torch",
    unitLabel: "feet",
    unitShort: "ft",
    answerNumeric: 305,
    answerDisplay: "305",
    difficulty: 2,
  },
  {
    id: "mix-moon-distance",
    pack: "mixed",
    category: "Distance",
    promptText: "Average distance from Earth to the Moon",
    unitLabel: "miles",
    unitShort: "mi",
    answerNumeric: 238_855,
    answerDisplay: "238,855",
    difficulty: 2,
  },
  {
    id: "mix-piano-keys",
    pack: "mixed",
    category: "Count",
    promptText: "Keys on a standard modern piano",
    unitLabel: "keys",
    unitShort: "keys",
    answerNumeric: 88,
    answerDisplay: "88",
    difficulty: 1,
  },
  {
    id: "mix-kilimanjaro-height",
    pack: "mixed",
    category: "Height",
    promptText: "Height of Mount Kilimanjaro",
    unitLabel: "meters",
    unitShort: "m",
    answerNumeric: 5_895,
    answerDisplay: "5,895",
    difficulty: 2,
  },
  {
    id: "mix-olympic-pool",
    pack: "mixed",
    category: "Volume",
    promptText: "Water held by an Olympic swimming pool",
    unitLabel: "liters",
    unitShort: "L",
    answerNumeric: 2_500_000,
    answerDisplay: "2,500,000",
    difficulty: 3,
  },
];
